### ISSUE TITLE
AdvancedBan

### ISSUE THREAD

**Issue by ghost** [vBagieta/CatCode-DOCS#3]
General:
  Prefix: "&7&l[&3&lKrystal&f&lSMP.pl&7&l] &f&l-"
  NoPerms: "&7&l[&3&lKrystal&f&lSMP.pl&7&l] &f&l- &c&lNieznana komenda!"
  LayoutNotFound: "&4Błąd: &cNie odnaleziono gracza o nazwie: %NAME%"
  TimeLayoutD: "%D% dni. %H% godz. %M% min. %S% sek."
  TimeLayoutH: "%H% godz. %M% min. %S% sek."
  TimeLayoutM: "%M% min. %S% sek."
  TimeLayoutS: "%S% sek."
  FailedFetch: "&4Błąd: &cNie udało się pobrać UUID %NAME%! Szczegółowe informacje można znaleźć w konsoli."

Ban:
  Usage: "&4Błąd: &cPoprawne użycie: /ban <nick> <powód blokady>"
  Done: "&cPomyślnie zablokowałeś gracza &4%NAME%&c."
  AlreadyDone: "&4Błąd: &cPodany gracz posiada już blokade konta!"
  Exempt: "&4Błąd: &cNie możesz zablokować konta tego gracza!"
  Layout:
  - '&c&lZostałeś/łaś permanentnie zablokowany/a na serwerze!'
  - '&7'
  - '&7Blokada nałożona przez: &c%OPERATOR%'
  - "&7Powód blokady: &c%REASON%"
  - '&7'
  - "&7Jeżeli uważasz, że blokada jest niesłuszna, zgłoś się"
  - '&7na naszego Discorda: &cdc.KrystalSMP.pl'
  - '&7'
  - '&7Zakup unbana na stronie &dwww.sklep.KrystalSMP.pl'
  - '&7'
  Notification:
  - "&cGracz &4%NAME% &czostał zablokowany na serwerze przez &4%OPERATOR% &cza &4%REASON%&c."
  UndoNotification: "&cAdministrator &4%OPERATOR% &codblokował konto gracza &4%NAME%&c."

Ipban:
  Usage: "&4Błąd: &cPoprawne użycie: /banip <nick,ip> <powód blokady>"
  Layout:
  - '&c&lZostałeś/łaś permanentnie zablokowany/a na serwerze!'
  - '&7'
  - '&7Blokada nałożona przez: &c%OPERATOR%'
  - "&7Powód blokady: &c%REASON%"
  - '&7'
  - "&7Jeżeli uważasz, że blokada jest niesłuszna, zgłoś się"
  - '&7na naszego Discorda: &cdc.KrystalSMP.pl'
  - '&7'
  - '&7Zakup unbana na stronie &dwww.sklep.KrystalSMP.pl'
  - '&7'
  Notification:
  - "&cGracz &4%NAME% &czostał zablokowany na serwerze przez &4%OPERATOR% &cza &4%REASON%&c."
  IpNotCashed: "&4Błąd: &cNie odnaleziono takiego gracza w bazie danych!"

Tempban:
  Usage: "&4Błąd: &cPoprawne użycie: /tempban <nick> <czas np. 10m 10h 10d> <powód blokady>"
  MaxDuration: "&4Błąd: &cNie możesz zbanować gracza powyżej %MAX% godzin."
  Layout:
  - '&c&lZostałeś/łaś czasowo zablokowany/a na serwerze!'
  - '&7'
  - '&7Blokada nałożona przez: &c%OPERATOR%'
  - "&7Powód blokady: &c%REASON%"
  - "&7Wygasa za: &c%DURATION%"
  - '&7'
  - "&7Jeżeli uważasz, że blokada jest niesłuszna, zgłoś się"
  - '&7na naszego Discorda: &cdc.KrystalSMP.pl'
  - '&7'
  - '&7Zakup unbana na stronie &dwww.sklep.KrystalSMP.pl'
  - '&7'
  Notification:
  - "&cGracz &4%NAME% &czostał zablokowany na serwerze przez &4%OPERATOR% &cna &4%DURATION% &cza &4%REASON%&c."

Tempipban:
  Usage: "&4Błąd: &cPoprawne użycie: /tempipban <nick> <czas np. 10m 10h 10d> <powód blokady>"
  MaxDuration: "&4Błąd: &cNie możesz zbanować gracza powyżej %MAX% godz."
  Layout:
  - '&c&lZostałeś/łaś czasowo zablokowany/a na serwerze!'
  - '&7'
  - '&7Blokada nałożona przez: &c%OPERATOR%'
  - "&7Powód blokady: &c%REASON%"
  - "&7Wygasa za: &c%DURATION%"
  - '&7'
  - "&7Jeżeli uważasz, że blokada jest niesłuszna, zgłoś się"
  - '&7na naszego Discorda: &cdc.KrystalSMP.pl'
  - '&7'
  - '&7Zakup unbana na stronie &dwww.sklep.KrystalSMP.pl'
  - '&7'
  Notification:
  - "&cGracz &4%NAME% &czostał zablokowany na serwerze przez &4%OPERATOR% &cna &4%DURATION% &cza &4%REASON%&c."

Mute:
  Usage: "&4Błąd: &cPoprawne użycie: /mute <nick> <powód>"
  Done: "&cPomyślnie wyciszyłeś gracza &4%NAME%&c."
  AlreadyDone: "&4Błąd: &cPodany gracz posiada już wyciszenie!"
  Exempt: "&4Błąd: &cNie możesz wyciszyć tego gracza!"
  Layout:
  - "&cZostałeś/łaś wyciszony/a na zawsze przez &4%OPERATOR% &cza &4%REASON%&c."
  Notification:
  - "&cGracz &4%NAME% &czostał/a wyciszony/a na zawsze przez &4%OPERATOR%&c."
  UndoNotification: "&cAdministrator &4%OPERATOR% &cusunął wyciszenie dla gracza &4%NAME%&c."

Tempmute:
  Usage: "&4Błąd: &cPoprawne użycie: /tempmute <nick> <czas np. 10m 10h 10d> <powód>"
  MaxDuration: "&4Błąd: &cNie możesz wyciszyć gracza powyżej %MAX% godz."
  Layout:
  - "&cZostałeś/łaś wyciszony/a na &4%DURATION% &cprzez &4%OPERATOR% &cza &4%REASON%&c."
  Notification:
  - "&cGracz &4%NAME% &czostał/a wyciszony/a na &4%DURATION% &cprzez &4%OPERATOR%&c."

Warn:
  Usage: "&4Błąd: &cPoprawne użycie: /warn <nick> <powód>"
  Done: "&cPomyślnie dałeś ostrzeżenie dla gracza &4%NAME%&c."
  Exempt: "&4Błąd: &cNie możesz ostrzec tego gracza!"
  Layout:
  - "&cZostałeś/łaś ostrzeżony/a &cprzez &4%OPERATOR% &cza &4%REASON%&c."
  - '&7Obecnie masz &c&o%COUNT% &7ostrzeżeń!'
  Notification:
  - "&cGracz &4%NAME% &czostał/a ostrzeżony/a za &4%REASON% &cprzez &4%OPERATOR%&c."

Tempwarn:
  Usage: "&4Błąd: &cPoprawne użycie: /tempwarn <nick> <czas np. 10m 10h 10d> <powód>"
  Done: "&cPomyślnie dałeś tymczasowe ostrzeżenie dla gracza &4%NAME%&c."
  Exempt: "&4Błąd: &cNie możesz tymczasowo ostrzec tego gracza!"
  Layout:
  - "&cZostałeś/łaś tymczasowo ostrzeżony/a &cprzez &4%OPERATOR% &cza &4%REASON%&c."
  - '&7Obecnie masz &c&o%COUNT% &7ostrzeżeń!'
  Notification:
  - "&cGracz &4%NAME% &czostał/a tymczasowo ostrzeżony/a za &4%REASON% &cprzez &4%OPERATOR%&c."

Kick:
  Usage: "&4Błąd: &cPoprawne użycie: /kick <nick> <powód>"
  Done: "&cPomyślnie wyrzuciłes gracza &4%NAME%&c."
  NotOnline: "&4Błąd: &cPodany gracz jest offline!"
  Exempt: "&4Błąd: &cNie możesz wyrzucić tego gracza!"
  Layout:
  - '&c&lZostałeś wyrzucony z serwera!'
  - '&7'
  - '&7Przez: &c%OPERATOR%'
  - "&7Powód: &c%REASON%"
  - '&7'
  Notification:
  - "&cGracz &4%NAME% &czostał wyrzucony z serwera przez &4%OPERATOR%&c."

UnBan:
  Notification: "&cAdministrator &4%OPERATOR% &codbanował gracza &4%NAME%&c."
  Usage: "&4Błąd: &cPoprawne użycie /unban <nick,ip>"
  NotPunished: "&4Błąd: &cPodany gracz nie jest zablokowany."
  Done: "&7Odblokowałeś gracza &a%NAME%&7."

UnMute:
  Notification: "&cAdministrator &4%OPERATOR% &cusunął wyciszenie gracza &4%NAME%&c."
  Usage: "&4Błąd: &cPoprawne użycie /unmute <nick>"
  NotPunished: "&4Błąd: &cPodany gracz nie jest wyciszony."
  Done: "&7Wyciszenie gracza &a%NAME% &7zostało usunięte."

UnWarn:
  Notification: "&cAdministrator &4%OPERATOR% &cusunął ostrzeżenie gracza &4%NAME%&c."
  Usage: "&4Błąd: &cPoprawne użycie /unwarn clear <nick>"
  NotFound: "&cNie znaleziono ostrzeżenia o ID: #%ID%"
  Done: "&7Ostrzerzenie gracza &a%NAME% &7zostało usunięte."
  Notification: "&cAdministrator &4%OPERATOR% &cusunął ostrzeżenie gracza &4%NAME%&c."
  Clear:
    Empty: "&7Gracz &c&o%NAME% &7nie ma żadnych ostrzeżeń!"
    Done: "&7Usunięto &7ostrzeżenie gracza &a&o%NAME%"

UnPunish:
    Usage: "&4Błąd: &cPoprawne użycie /unpunish <ID>"
    NotFound: "&cNie znaleziono kary o ID: #%ID%"
    Done: "&7Usunięto &7karę gracza &a&o%NAME%"

Banlist:
  Usage: "&4Błąd: &cPoprawne użycie /banlist <strona>"
  OutOfIndex: "&4Błąd: &cNie znaleziono podanej strony!"
  NoEntries: "&4Błąd: &cNie odnaleziono żadnych banów."
  Header:
  - "&4&lLista blokad:"
  Entry:
  - " &8&m---------------------------"
  - "  &8[&4%NAME% &7dnia &c%DATE%&8]"
  - "  &7Na: &c%DURATION%"
  - "  &7Przez: &c%OPERATOR%"
  - "  &7Typ bana: &c%TYPE%"
  - "  &7Z powodu: &c%REASON%"
  - " &8&m---------------------------"
  Footer: "&7Strona: &c%CURRENT_PAGE% &7z &c%TOTAL_PAGES% &8| &7Wszystkich banów: &c%COUNT%"
  PageFooter: " "

History:
  Usage: "&4Błąd: &cPoprawne użycie: /history <nick,ip> <strona>"
  OutOfIndex: "&4Błąd: &cNie znaleziono podanej strony!"
  NoEntries: "&4Błąd: &cNie odnaleziono żadnych ostrzeżeń gracza %NAME%."
  Header:
  - "&4&lHistoria banów gracza %NAME%:"
  Entry:
  - " &8&m---------------------------"
  - "  &8[&7Dnia &c%DATE%&8]"
  - "  &7Na: &c%DURATION%"
  - "  &7Przez: &c%OPERATOR%"
  - "  &7Typ bana: &c%TYPE%"
  - "  &7Z powodu: &c%REASON%"
  - " &8&m---------------------------"
  Footer: "&7Strona: &c%CURRENT_PAGE% &7z &c%TOTAL_PAGES% &8| &7Wszystkich banów: &c%COUNT%"
  PageFooter: " "

Warns:
  Usage: "&4Błąd: &cPoprawne użycie /warnlist <nick> <strona>"
  OutOfIndex: "&4Błąd: &cNie znaleziono podanej strony!"
  NoEntries: "&4Błąd: &cNie odnaleziono żadnych ostrzeżeń."
  Header:
  - "&4&lLista ostrzeżeń:"
  Entry:
  - " &8&m---------------------------"
  - "  &8[&4%NAME% &7dnia &c%DATE%&8]"
  - "  &7Przez: &c%OPERATOR%"
  - "  &7Typ ostrzeżenia: &c%TYPE%"
  - "  &7Z powodu: &c%REASON%"
  - " &8&m---------------------------"
  Footer: "&7Strona: &c%CURRENT_PAGE% &7z &c%TOTAL_PAGES% &8| &7Wszystkich ostrzeżeń: &c%COUNT%"
  PageFooter: " "

WarnsOwn:
  OutOfIndex: "&4Błąd: &cNie znaleziono podanej strony!"
  NoEntries: "&4Błąd: &cNie odnaleziono żadnych ostrzeżeń."
  Header:
  - "&4&lTwoje ostrzeżenia:"
  Entry:
  - " &8&m---------------------------"
  - "  &8[&4%NAME% &7dnia &c%DATE%&8]"
  - "  &7Przez: &c%OPERATOR%"
  - "  &7Typ ostrzeżenia: &c%TYPE%"
  - "  &7Z powodu: &c%REASON%"
  - " &8&m---------------------------"
  Footer: "&7Strona: &c%CURRENT_PAGE% &7z &c%TOTAL_PAGES% &8| &7Wszystkich ostrzeżeń: &c%COUNT%"
  PageFooter: " "

ChangeReason:
  Usage: "&4Błąd: &cPoprawne użycie /change-reason <nick> <nowy powód>"
  Done: "&7Kara o ID: &a&o#%ID% &7została zmieniona!"
  NotFound: "&cNie znaleziono takiej kary"

Check:
  BanReason: "  &cReason &8\xbb &7%REASON%"
  MuteReason: "  &cReason &8\xbb &7%REASON%"
  Note: "&cNotes &8» &7%COUNT%"
  BanReason: "  &cReason &8\xbb &7%REASON%"
  MuteReason: "  &cReason &8\xbb &7%REASON%"
  Note: "&cNotes &8» &7%COUNT%"
  BanReason: "  &cReason &8\xbb &7%REASON%"
  MuteReason: "  &cReason &8\xbb &7%REASON%"
  Note: "&cNotes &8» &7%COUNT%"
  Usage: "&4Błąd: &cPoprawne użycie /check <nick>"
  Header: "&7Gracz: &c&l%NAME%&7:"
  UUID: " &7UUID: &c%UUID%"
  IP: " &7IP: &c%IP%"
  Geo: " &7Kraj: &c%LOCATION%"
  Mute: " &7Wyciszony/a: &c%DURATION%"
  MuteReason: "  &7Powód: &c%REASON%"
  Ban: " &7Zbanowany/a: &c%DURATION%"
  BanReason: "  &7Powód: &c%REASON%"
  Warn: " &7Ostrzerzeń: &c%COUNT%"
  Note: " &7Notatek: &c%COUNT%"
  NotFound: "&4Błąd: &cNie znaleziono gracza w bazie danych."
  Cached: "&aTak."
  NotCached: "&cNie."

**Comment by vbagieta** [comment]
Dodam potem.
